name: Scope Testing

on: [push]

jobs:
  scope:
    runs-on: macOS-latest
    
    steps:
      - name: Check if SCOPE_DSN is set
        run: if [ "${{secrets.SCOPE_DSN}}" = "" ]; then exit 1; fi
      - name: Checkout
        uses: actions/checkout@v1
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.app
      - name: Build and test
        run: |
          pod update
          xcodebuild test -workspace ScopeAgent-Reference.xcworkspace -scheme ScopeAgent-Reference -destination 'platform=iOS Simulator,name=iPhone 11' 
        env:
          SCOPE_DSN: ${{secrets.SCOPE_DSN}}
